// Author annotations for major spikes — curated narrative callouts
const ANNOTATIONS = [
    {
        date: "20200315",
        article: "COVID-19_pandemic",
        title: "WHO declares pandemic",
        text: "The World Health Organization declared COVID-19 a global pandemic on March 11, 2020. Wikipedia pageviews surged to millions per day as people sought information.",
        insight: "Pattern to notice: The spike is extraordinarily tall and steep, but attention remains elevated for weeks — a signature of an ongoing crisis where people keep returning for updates, unlike one-off news events that decay within days.",
        compareTopic: "Barbie_(film)",
        compareLabel: "Compare: crisis spike (COVID) vs. entertainment long tail (Barbie)",
    },
    {
        date: "20211110",
        article: "Bitcoin",
        title: "Bitcoin tops $68K",
        text: "Bitcoin reached a new all-time high above $68,000 in November 2021, triggering a sharp spike in Wikipedia interest as crypto speculation intensified.",
        insight: "Pattern to notice: Bitcoin shows recurring spikes that align with price milestones — a 'serial spike' pattern. Each cycle reaches a sharp peak then drops quickly, reflecting speculative hype rather than sustained learning.",
    },
    {
        date: "20220224",
        article: "2022_Russian_invasion_of_Ukraine",
        title: "Russia invades Ukraine",
        text: "Russia launched a full-scale invasion of Ukraine on February 24, 2022. The article became one of Wikipedia's most-viewed pages overnight.",
        insight: "Pattern to notice: The invasion spike is among the sharpest in the dataset — nearly vertical on day one. Compare how the geopolitical crisis commands abrupt, concentrated attention versus the president whose attention builds gradually over a campaign season.",
        compareTopic: "Donald_Trump",
        compareLabel: "Compare: sudden war spike vs. slow political buildup (Trump 2024)",
    },
    {
        date: "20220908",
        article: "Queen_Elizabeth_II",
        title: "Queen Elizabeth II dies",
        text: "Queen Elizabeth II passed away on September 8, 2022, after 70 years on the throne. Her Wikipedia page received record-breaking traffic.",
        insight: "Pattern to notice: A single-day mega-spike followed by a rapid but multi-step decay — the mourning period creates a 'staircase' decline as each funeral event briefly re-elevates interest.",
    },
    {
        date: "20221120",
        article: "FIFA_World_Cup",
        title: "2022 World Cup kicks off",
        text: "The FIFA World Cup in Qatar began on November 20, 2022 — the first winter World Cup. Pageviews spiked during key matches.",
        insight: "Pattern to notice: Unlike a single spike, the World Cup creates a 'comb' pattern — a cluster of repeated spikes spread across the tournament, each peak aligning with knockout-round matches. Scheduled events produce predictable, periodic attention.",
        compareTopic: "Super_Bowl",
        compareLabel: "Compare: month-long tournament comb (World Cup) vs. single-day event spike (Super Bowl)",
    },
    {
        date: "20221130",
        article: "ChatGPT",
        title: "ChatGPT launches",
        text: "OpenAI released ChatGPT on November 30, 2022. The chatbot went viral, gaining a million users in 5 days and driving enormous curiosity.",
        insight: "Pattern to notice: ChatGPT's spike doesn't decay to near-zero — it settles at a permanently elevated baseline. This 'step change' pattern signals a topic that entered mainstream vocabulary and stayed, unlike viral moments that fade completely.",
        compareTopic: "Ever_Given",
        compareLabel: "Compare: permanent baseline shift (ChatGPT) vs. viral flash that vanishes (Ever Given)",
    },
    {
        date: "20231007",
        article: "Hamas",
        title: "Hamas attacks Israel",
        text: "On October 7, 2023, Hamas launched a large-scale attack on Israel, causing a massive surge in pageviews for related articles.",
        insight: "Pattern to notice: The spike is extremely sharp — a near-vertical jump from a low baseline. Crisis articles that were previously obscure can go from thousands to millions of views within hours, showing how conflict instantly reshapes public attention.",
    },
    {
        date: "20230721",
        article: "Oppenheimer_(film)",
        title: "Barbenheimer weekend",
        text: "Oppenheimer and Barbie opened on the same weekend (July 21, 2023), creating a cultural phenomenon dubbed 'Barbenheimer.'",
        insight: "Pattern to notice: Two films released on the same day create nearly synchronized spikes — a rare 'twin peak' event. Notice how both rise together, but Barbie sustains a longer tail, suggesting different audience engagement patterns even for simultaneous releases.",
        compareTopic: "Barbie_(film)",
        compareLabel: "Compare: Barbenheimer twins — same launch day, different decay shapes",
    },
    {
        date: "20230806",
        article: "Barbie_(film)",
        title: "Barbie passes $1B",
        text: "Barbie crossed the $1 billion box-office mark in early August 2023, turning sustained hype into a longer second wave of public attention.",
        insight: "Pattern to notice: Barbie's attention curve has a broad 'plateau' shape — a cultural phenomenon that sustains interest over weeks rather than a single spike. The $1B milestone creates a visible second bump, showing how milestones can re-ignite attention.",
    },
    {
        date: "20210323",
        article: "Ever_Given",
        title: "Suez Canal blocked",
        text: "The container ship Ever Given ran aground in the Suez Canal on March 23, 2021, blocking global trade for six days and captivating the world.",
        insight: "Pattern to notice: A textbook 'flash spike' — enormous peak that decays to almost zero within two weeks. The topic had virtually no baseline interest before or after, making it one of the purest examples of ephemeral viral attention in the dataset.",
        compareTopic: "ChatGPT",
        compareLabel: "Compare: flash spike that vanishes (Ever Given) vs. lasting baseline shift (ChatGPT)",
    },
    {
        date: "20210927",
        article: "Squid_Game",
        title: "Squid Game goes viral",
        text: "Netflix's Squid Game became a global phenomenon in late September 2021, becoming the platform's most-watched series ever.",
        insight: "Pattern to notice: Entertainment virality builds over days (not instantly like crisis events) as word-of-mouth spreads. The peak is broad and the decay is gradual — people binge at different times, stretching the attention window wider than a news event.",
        compareTopic: "2022_Russian_invasion_of_Ukraine",
        compareLabel: "Compare: slow entertainment build (Squid Game) vs. instant crisis spike (Ukraine invasion)",
    },
    {
        date: "20200601",
        article: "Black_Lives_Matter",
        title: "George Floyd protests",
        text: "Following the murder of George Floyd on May 25, 2020, Black Lives Matter protests erupted worldwide, driving massive Wikipedia traffic.",
        insight: "Pattern to notice: The spike has an unusually long 'shoulder' — attention stays elevated for weeks as protests continued worldwide. Social movements sustain attention longer than one-off events because new developments keep feeding the cycle.",
    },
    {
        date: "20230618",
        article: "Titan_submersible_implosion",
        title: "Titan sub disappears",
        text: "The Titan submersible lost contact on June 18, 2023, during a dive to the Titanic wreck. The five-day search captivated global attention.",
        insight: "Pattern to notice: The five-day search creates a 'suspense plateau' — attention stays high and flat while the outcome is unknown, then drops sharply once resolved. This is a distinct pattern from instant-resolution events.",
        compareTopic: "Queen_Elizabeth_II",
        compareLabel: "Compare: suspense plateau (Titan search) vs. instant resolution then mourning decay (Queen Elizabeth)",
    },
    {
        date: "20241105",
        article: "Donald_Trump",
        title: "Trump wins 2024 election",
        text: "Donald Trump won the 2024 presidential election on November 5, driving record Wikipedia pageviews for political articles.",
        insight: "Pattern to notice: Political figures have a high, volatile baseline — Trump's article never drops to near-zero. The election spike sits on top of an already-elevated floor, unlike entertainment or disaster topics that spike from near-zero.",
        compareTopic: "Titan_submersible_implosion",
        compareLabel: "Compare: high volatile baseline (Trump) vs. zero-to-spike flash (Titan sub)",
    },
    {
        date: "20240210",
        article: "Taylor_Swift",
        title: "Swift at the Super Bowl",
        text: "Taylor Swift's relationship with Travis Kelce brought unprecedented attention to the Super Bowl LVIII in February 2024.",
        insight: "Pattern to notice: Celebrity topics show a 'rolling hills' pattern — multiple moderate spikes tied to albums, tours, and media moments. No single spike dominates; instead, sustained cultural relevance creates a consistently elevated baseline.",
        compareTopic: "Travis_Kelce",
        compareLabel: "Compare: the Swift-Kelce effect — see how both timelines spike together at the Super Bowl",
    },
];
